// Isolated UI verification. All API / WebSocket data is mocked; no controller is contacted.
import { chromium } from '../.qa/node_modules/playwright/index.mjs'
import { createServer } from 'node:http'
import { readFile, mkdir } from 'node:fs/promises'
import { resolve, extname } from 'node:path'
import assert from 'node:assert/strict'
import { fixtureScene } from './fixtures/scene3dFixture.js'

const root = resolve('.verify-dist')
const server = createServer(async (req, res) => {
  const pathname = new URL(req.url, 'http://localhost').pathname
  const path = resolve(root, `.${pathname === '/' || !extname(pathname) ? '/index.html' : pathname}`)
  if (!path.startsWith(root)) { res.writeHead(403).end(); return }
  try {
    const data = await readFile(path)
    const type = { '.html': 'text/html', '.js': 'text/javascript', '.css': 'text/css', '.svg': 'image/svg+xml' }[extname(path)] || 'application/octet-stream'
    res.writeHead(200, { 'Content-Type': type }); res.end(data)
  } catch { res.writeHead(404).end() }
})
await new Promise(done => server.listen(0, '127.0.0.1', done))
await mkdir('.qa/results', { recursive: true })
const browser = await chromium.launch({ executablePath: 'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe', headless: true, args: ['--enable-unsafe-swiftshader'] })
const context = await browser.newContext({ viewport: { width: 1600, height: 1000 }, acceptDownloads: true })
const page = await context.newPage()
const errors = [], writes = []
let socketCount = 0, runningValue = 1, quality = 'GOOD'
const variables = [{ id: 7, name: '泵运行', source: 'OPCUA', resourceId: 'r-1', unit: '' }, { id: 8, name: '储罐液位', source: 'OPCUA', resourceId: 'r-1', unit: '%' }]
const points = () => [{ varId: 7, value: runningValue, quality, timestamp: Date.now() }, { varId: 8, value: 68.5, quality, timestamp: Date.now() }]
page.on('pageerror', error => errors.push(error.message))
page.on('console', msg => { if (msg.type() === 'warning' && /3D initialization|THREE/.test(msg.text())) errors.push(msg.text()) })
await page.route('**/api/**', route => {
  const path = new URL(route.request().url()).pathname
  if (route.request().method() !== 'GET') writes.push(path)
  const payload = path === '/api/variables' ? variables : path === '/api/realtime' ? points() : path === '/api/status' ? { opcuaServer: true, database: true } : path === '/api/network/urls' ? {} : path.startsWith('/api/historydb') ? { columns: ['id', 'time'], rows: [] } : []
  return route.fulfill({ contentType: 'application/json', body: JSON.stringify(payload) })
})
await page.routeWebSocket('**/ws/realtime*', ws => { socketCount++; ws.send(JSON.stringify(points())) })
await page.addInitScript(({ initialScene }) => {
  // Exercise the download fallback; a native Save dialog cannot be driven in headless mode.
  window.showSaveFilePicker = undefined
  if (localStorage.getItem('qa-initialized')) return
  localStorage.setItem('qa-initialized', '1')
  localStorage.setItem('auth_token', 'isolated-test-token')
  localStorage.setItem('auth_username', 'UI测试')
  localStorage.setItem('monitor-widget-layout', JSON.stringify({ widgets: [{ id: 'w-pump', type: 'processPump', x: 60, y: 60, w: 120, h: 100, config: { label: '共用水泵', varId: 7 } }], connections: [], scene3d: initialScene }))
}, { initialScene: fixtureScene() })
const click = name => page.getByRole('button', { name, exact: true }).click()
const cameraState = () => page.evaluate(() => JSON.parse(localStorage.getItem('monitor-widget-layout')).scene3d.camera)
const cameraDistance = camera => Math.hypot(...camera.position.map((value, index) => value - camera.target[index]))
const checkMiddlePan = async locator => {
  await page.waitForTimeout(400)
  const before = await cameraState()
  const box = await locator.boundingBox()
  const x = box.x + box.width / 2, y = box.y + box.height / 2
  await page.mouse.move(x, y); await page.mouse.down({ button: 'middle' })
  await page.mouse.move(x + 60, y + 30, { steps: 12 }); await page.mouse.up({ button: 'middle' })
  await page.waitForTimeout(400)
  const after = await cameraState()
  assert.ok(Math.hypot(...after.target.map((value, index) => value - before.target[index])) > 0.1, 'middle drag pans camera target')
  assert.ok(Math.abs(cameraDistance(after) - cameraDistance(before)) < 0.01, 'middle drag preserves zoom distance')
}
const resizePanel = async (name, selector, dx, dy, { verifyLive3d = false } = {}) => {
  const panel = page.locator(selector)
  const before = await panel.boundingBox()
  const drawingBufferBefore = verifyLive3d
    ? await page.locator('.industrial-webgl').evaluate(canvas => [canvas.width, canvas.height])
    : null
  const handle = await page.getByRole('separator', { name, exact: true }).boundingBox()
  const x = handle.x + handle.width / 2, y = handle.y + handle.height / 2
  await page.mouse.move(x, y); await page.mouse.down()
  await page.mouse.move(x + dx, y + dy, { steps: 8 })
  let drawingBufferDuring = null
  if (verifyLive3d) {
    await page.evaluate(() => new Promise(resolveFrame => requestAnimationFrame(() => requestAnimationFrame(resolveFrame))))
    assert.equal(await page.locator('.scene-render-host').evaluate(node => node.classList.contains('is-panel-resizing')), true, '3D renderer enters resize mode')
    drawingBufferDuring = await page.locator('.industrial-webgl').evaluate(canvas => [canvas.width, canvas.height])
    const cssBounds = await page.locator('.industrial-webgl').boundingBox()
    assert.notDeepEqual(drawingBufferDuring, drawingBufferBefore, '3D drawing buffer follows the panel while dragging')
    assert.ok(Math.abs(drawingBufferDuring[0] / drawingBufferDuring[1] - cssBounds.width / cssBounds.height) < 0.01, '3D buffer and visible canvas keep the same aspect ratio')
  }
  await page.mouse.up()
  if (verifyLive3d) {
    await page.waitForTimeout(100)
    assert.equal(await page.locator('.scene-render-host').evaluate(node => node.classList.contains('is-panel-resizing')), false, '3D renderer exits resize mode')
    assert.deepEqual(await page.locator('.industrial-webgl').evaluate(canvas => [canvas.width, canvas.height]), drawingBufferDuring, 'releasing the divider causes no delayed size correction')
  }
  const after = await panel.boundingBox()
  const actual = dy ? after.height - before.height : after.width - before.width
  assert.ok(Math.abs(actual - Math.max(Math.abs(dx), Math.abs(dy))) < 2, `${name}: expected resize, got ${actual}`)
  assert.equal(await page.evaluate(() => document.body.style.userSelect), '')
  return after
}
const waitText = async (selector, text) => {
  await page.waitForFunction(({ selector, text }) => document.querySelector(selector)?.textContent.includes(text), { selector, text })
}
try {
  await page.goto(`http://127.0.0.1:${server.address().port}/canvas`)
  await page.locator('.widget-wrapper[data-widget-id="w-pump"]').click()
  await page.getByTitle('编辑组件', { exact: true }).click()
  await resizePanel('拖动调整 2D 右侧属性栏宽度', '.config-pane', -180, 0)
  const componentNameInput = page.getByLabel('组件名称', { exact: true })
  assert.equal(await componentNameInput.inputValue(), '共用水泵')
  await componentNameInput.fill('二号供水泵')
  await componentNameInput.press('Tab')
  await waitText('.widget-wrapper[data-widget-id="w-pump"]', '二号供水泵')
  await page.screenshot({ path: '.qa/results/2d-resized-properties.png' })
  const twoDToolbarButton = await page.locator('.canvas-toolbar-mini .btn').first().evaluate(node => ({ height: getComputedStyle(node).height, radius: getComputedStyle(node).borderRadius, font: getComputedStyle(node).fontSize }))
  await click('3D')
  await page.locator('.industrial-webgl').waitFor()
  assert.equal(await page.locator('.scene-center > .scene-toolbar').count(), 1)
  assert.equal(await page.locator('.canvas-action-toolbar').count(), 1)
  assert.equal(await page.locator('.library-foot').count(), 0)
  const threeDToolbarButton = await page.locator('.scene-toolbar .btn').first().evaluate(node => ({ height: getComputedStyle(node).height, radius: getComputedStyle(node).borderRadius, font: getComputedStyle(node).fontSize }))
  assert.deepEqual(threeDToolbarButton, twoDToolbarButton, '3D toolbar follows 2D button sizing and typography')
  assert.equal(await page.locator('.scene-toolbar .scene-tool-icon').count(), 5)
  assert.equal(await page.getByRole('button', { name: '切换 2D', exact: true }).count(), 0)
  const sidebarFontSizes = await page.locator('.scene-library .model-card, .scene-inspector .inspector-field').evaluateAll(nodes => nodes.map(node => parseFloat(getComputedStyle(node).fontSize)))
  assert.ok(sidebarFontSizes.length > 0 && sidebarFontSizes.every(size => size >= 14), 'both sidebars have readable larger text')
  const sceneTextSizes = await page.locator('.viewport-tool-group button, .scene-legend, .scene-navigation-hint, .data-tabs button, .device-status-card > span, .device-status-card > small').evaluateAll(nodes => nodes.map(node => parseFloat(getComputedStyle(node).fontSize)))
  assert.ok(sceneTextSizes.length > 0 && sceneTextSizes.every(size => size >= 12), 'viewport corners and bottom dock use readable text')
  const firstModelCard = page.locator('.model-card').first()
  await firstModelCard.hover()
  await page.getByRole('tooltip').waitFor()
  assert.equal(await page.getByRole('tooltip').locator('canvas').count(), 1, 'hover preview renders the actual 3D model')
  const previewBounds = await page.getByRole('tooltip').boundingBox()
  assert.ok(previewBounds.x > (await page.locator('.scene-library').boundingBox()).x + 100, 'model preview opens beside the library')
  await page.screenshot({ path: '.qa/results/3d-library-model-preview.png' })
  await page.mouse.move(900, 500)
  await page.getByRole('button', { name: '折叠工业组件库', exact: true }).click()
  assert.equal(await page.locator('.library-section-body').isVisible(), false)
  await page.getByRole('button', { name: '展开工业组件库', exact: true }).click()
  assert.equal(await page.locator('.library-section-body').isVisible(), true)
  await page.getByRole('button', { name: '折叠场景设备', exact: true }).click()
  assert.equal(await page.locator('.scene-devices-body').isVisible(), false)
  await page.getByRole('button', { name: '展开场景设备', exact: true }).click()
  assert.equal(await page.locator('.scene-devices-body').isVisible(), true)
  assert.equal(await page.locator('.scene-settings-intro').count(), 0)
  assert.equal(await page.getByText('现场，一目了然。', { exact: true }).count(), 0)
  assert.equal(await page.getByRole('button', { name: '载入泵站示范场景', exact: true }).count(), 0)
  assert.equal(await page.getByText('供水泵站示范场景', { exact: true }).count(), 0)
  await resizePanel('拖动调整 3D 左侧组件栏宽度', '.scene-library', 90, 0, { verifyLive3d: true })
  await resizePanel('拖动调整 3D 右侧属性栏宽度', '.scene-inspector', -100, 0)
  await resizePanel('拖动调整 3D 下侧数据栏高度', '.scene-data-dock', 0, -100)
  const panelSizes = await page.evaluate(() => ['.scene-library', '.scene-inspector', '.scene-data-dock'].map(selector => { const rect = document.querySelector(selector).getBoundingClientRect(); return [rect.width, rect.height] }))
  const fontFamilies = await page.locator('.scene-inspector, .scene-toolbar button, .scene-counts strong').evaluateAll(nodes => nodes.map(node => getComputedStyle(node).fontFamily))
  assert.ok(fontFamilies.every(font => font.startsWith('"Times New Roman"') && font.includes('SimSun')), 'all scene text uses shared Latin / Chinese font stack')
  const cdp = await context.newCDPSession(page)
  await cdp.send('DOM.enable'); await cdp.send('CSS.enable')
  const { root: documentRoot } = await cdp.send('DOM.getDocument')
  const chineseNode = await cdp.send('DOM.querySelector', { nodeId: documentRoot.nodeId, selector: '.scene-inspector .panel-heading strong' })
  const latinNode = await cdp.send('DOM.querySelector', { nodeId: documentRoot.nodeId, selector: '.scene-inspector .panel-heading > span' })
  const chineseFonts = await cdp.send('CSS.getPlatformFontsForNode', { nodeId: chineseNode.nodeId })
  const latinFonts = await cdp.send('CSS.getPlatformFontsForNode', { nodeId: latinNode.nodeId })
  assert.ok(chineseFonts.fonts.some(font => /SimSun|宋体/i.test(font.familyName) && font.glyphCount > 0), 'Chinese glyphs render in SimSun')
  assert.ok(latinFonts.fonts.some(font => /Times New Roman/i.test(font.familyName) && font.glyphCount > 0), 'Latin glyphs render in Times New Roman')
  await cdp.detach()
  await page.getByLabel('设备名称统一字号（px）', { exact: true }).fill('18')
  await page.getByLabel('设备名称统一字号（px）', { exact: true }).press('Tab')
  await page.waitForTimeout(1200)
  const deviceGrid = await page.locator('.device-status-list').evaluate(node => ({
    clientWidth: node.clientWidth,
    scrollWidth: node.scrollWidth,
    rows: new Set([...node.querySelectorAll('.device-status-card')].map(card => card.offsetTop)).size
  }))
  assert.ok(deviceGrid.scrollWidth <= deviceGrid.clientWidth + 1, 'device status grid never needs horizontal scrolling')
  assert.ok(deviceGrid.rows > 1, 'device status cards wrap into vertical rows')
  await checkMiddlePan(page.locator('.industrial-webgl'))
  await click('总览')
  await page.waitForTimeout(1000)
  await click('侧视')
  await page.waitForTimeout(1100)
  const sideCamera = await cameraState()
  await click('俯视')
  await page.waitForTimeout(220)
  assert.deepEqual(await cameraState(), sideCamera, 'view transition does not jump directly to its destination')
  await page.waitForTimeout(900)
  assert.notDeepEqual(await cameraState(), sideCamera, 'view transition reaches and persists its destination')
  await click('总览')
  await page.waitForTimeout(900)
  const cameraBeforeDoubleClick = await cameraState()
  await page.locator('.industrial-device-label', { hasText: '输送泵 P-101' }).dblclick()
  await page.waitForTimeout(1000)
  assert.equal(await page.locator('.tree-row.selected .tree-select', { hasText: '输送泵 P-101' }).count(), 1, 'double-clicking a canvas device selects it')
  assert.notDeepEqual(await cameraState(), cameraBeforeDoubleClick, 'double-clicking a canvas device focuses the camera')
  const sceneComponentName = page.getByLabel('组件名称', { exact: true })
  await sceneComponentName.fill('')
  await sceneComponentName.pressSequentially('三维输送泵 P-101', { delay: 80 })
  await page.waitForTimeout(600)
  assert.equal(await sceneComponentName.inputValue(), '三维输送泵 P-101', 'realtime rerenders must not erase a name being edited')
  await sceneComponentName.press('Tab')
  await page.locator('.industrial-device-label', { hasText: '三维输送泵 P-101' }).waitFor()
  const nameSize = page.getByLabel('名称字号（px）', { exact: true })
  assert.equal(await nameSize.inputValue(), '18')
  await nameSize.fill('26'); await nameSize.press('Tab')
  const pumpLabel = page.locator('.industrial-device-label', { hasText: '输送泵 P-101' })
  assert.equal(await pumpLabel.locator('strong').evaluate(node => getComputedStyle(node).fontSize), '26px')
  await click('使用场景统一字号')
  assert.equal(await nameSize.inputValue(), '18')
  await nameSize.fill('26'); await nameSize.press('Tab')
  await checkMiddlePan(pumpLabel)
  await click('总览')
  await page.waitForTimeout(400)
  const beforeZoom = await cameraState()
  const canvasBox = await page.locator('.industrial-webgl').boundingBox()
  await page.mouse.move(canvasBox.x + canvasBox.width / 2, canvasBox.y + canvasBox.height / 2)
  await page.mouse.wheel(0, 150)
  await page.waitForTimeout(400)
  assert.ok(Math.abs(cameraDistance(await cameraState()) - cameraDistance(beforeZoom)) > 0.1, 'wheel scroll still zooms')
  await click('总览')
  await page.getByLabel('跟随 2D 组件').selectOption('w-pump')
  await waitText('.device-summary', '运行')
  await page.getByLabel('位置 X', { exact: true }).fill('-3.5')
  await page.getByLabel('位置 X', { exact: true }).press('Tab')
  await page.locator('.scene-history button').first().click()
  assert.equal(await page.getByLabel('位置 X', { exact: true }).inputValue(), '-2.4')
  await page.locator('.scene-history button').last().click()
  assert.equal(await page.getByLabel('位置 X', { exact: true }).inputValue(), '-3.5')
  const stageBoundsBeforeNotice = await page.locator('.scene-stage').boundingBox()
  await page.keyboard.press('Control+C')
  await page.keyboard.press('Control+V')
  assert.equal(await page.locator('.tree-row').count(), 11, 'Ctrl+V pastes the copied device')
  assert.match(await page.getByLabel('组件名称', { exact: true }).inputValue(), /副本/, 'pasted device receives a distinct name')
  assert.deepEqual(await page.locator('.scene-stage').boundingBox(), stageBoundsBeforeNotice, 'showing an operation notice does not resize the 3D canvas')
  await page.locator('.scene-notice').waitFor({ state: 'detached', timeout: 4500 })
  assert.deepEqual(await page.locator('.scene-stage').boundingBox(), stageBoundsBeforeNotice, 'hiding an operation notice does not resize the 3D canvas')
  await page.keyboard.press('Control+Z')
  assert.equal(await page.locator('.tree-row').count(), 10, 'Ctrl+Z undoes the paste')
  await page.locator('.tree-select', { hasText: '三维输送泵 P-101' }).click()
  await click('复制设备')
  assert.equal(await page.locator('.tree-row').count(), 11)
  await click('删除')
  assert.equal(await page.locator('.tree-row').count(), 10)
  await page.locator('.tree-select', { hasText: '原水储罐 T-101' }).click()
  await page.getByLabel('数值 / 液位变量').selectOption('8')
  await waitText('.device-summary', '68.5')
  await click('总览')
  await page.screenshot({ path: '.qa/results/3d-editor-light.png' })
  await click('保存')
  await page.getByPlaceholder('例如：一号产线监控').fill('3D集成测试泵站')
  await page.locator('.project-form-dialog').getByRole('button', { name: '保存', exact: true }).click()
  await page.locator('.project-form-dialog').waitFor({ state: 'hidden' })
  await page.locator('.pm-header .btn-icon').click()
  await page.waitForFunction(() => JSON.parse(localStorage.getItem('monitor-projects') || '[]').length === 1)
  const saved = await page.evaluate(() => JSON.parse(localStorage.getItem('monitor-projects'))[0])
  assert.equal(saved.layout.widgets.length, 1)
  assert.equal(saved.layout.scene3d.nodes.length, 10)
  await click('项目')
  const managerBounds = await page.locator('.dialog-project-manager').boundingBox()
  assert.ok(managerBounds.width >= 1000, 'project manager uses the enlarged desktop width')
  const projectCardBounds = await page.locator('.project-card').first().boundingBox()
  const lastProjectButtonBounds = await page.locator('.project-card .project-actions button').last().boundingBox()
  assert.ok(lastProjectButtonBounds.x + lastProjectButtonBounds.width <= projectCardBounds.x + projectCardBounds.width, 'project buttons stay inside the enlarged card')
  const projectDownloadPromise = page.waitForEvent('download')
  await click('导出当前画布')
  await (await projectDownloadPromise).saveAs('.qa/results/project-export.json')
  const projectExport = JSON.parse(await readFile('.qa/results/project-export.json', 'utf8'))
  assert.equal(projectExport.version, 2)
  assert.equal(projectExport.project.layout.scene3d.nodes.length, 10)
  assert.equal(projectExport.variableReferences.length, 2)
  await page.locator('.pm-file-input').setInputFiles('.qa/results/project-export.json')
  await waitText('.pm-note', '已从')
  const importedProjects = await page.evaluate(() => JSON.parse(localStorage.getItem('monitor-projects')))
  assert.equal(importedProjects.length, 2)
  assert.deepEqual(importedProjects[1].layout.scene3d, saved.layout.scene3d)
  await page.locator('.pm-header .btn-icon').click()
  const downloadedPromise = page.waitForEvent('download')
  await click('导出 3D JSON')
  const downloaded = await downloadedPromise
  await downloaded.saveAs('.qa/results/scene-export.json')
  const exported = JSON.parse(await readFile('.qa/results/scene-export.json', 'utf8'))
  assert.equal(exported.scene3d.nodes.length, 10)
  assert.equal(exported.scene3d.nodes.find(n => n.type === 'pump').name, '三维输送泵 P-101')
  assert.equal(exported.scene3d.environment.labelFontSize, 18)
  assert.equal(exported.scene3d.nodes.find(n => n.type === 'pump').labelFontSize, 26)
  assert.equal(exported.scene3d.nodes.find(n => n.type === 'pump').bindings.status, '7')
  assert.equal(exported.scene3d.nodes.find(n => n.type === 'pump').linkedWidgetId, null)
  await click('2D')
  await page.locator('.canvas-page').waitFor()
  assert.equal(await page.locator('.process-pump').first().getAttribute('class').then(c => c.includes('active')), true)
  await click('3D')
  await page.locator('.tree-select', { hasText: '输送泵 P-101' }).click()
  await waitText('.device-summary', '运行')
  runningValue = 0
  await waitText('.device-summary', '停止')
  quality = 'BAD'
  await waitText('.device-summary', '质量异常')
  quality = 'GOOD'; runningValue = 1
  await waitText('.device-summary', '运行')
  await click('应用模式')
  assert.equal(await page.locator('.scene-library').count(), 0)
  assert.equal(await page.locator('.scene-inspector, .scene-data-dock, .scene-toolbar, .viewport-toolbar, .pane-resize-handle').count(), 0)
  const fullCanvas = await page.locator('.industrial-webgl').boundingBox()
  assert.deepEqual([fullCanvas.x, fullCanvas.y, fullCanvas.width, fullCanvas.height], [0, 0, 1600, 1000])
  await checkMiddlePan(page.locator('.industrial-webgl'))
  await page.screenshot({ path: '.qa/results/3d-application-canvas-only.png' })
  await page.keyboard.press('F2')
  await page.locator('.application-overlay').waitFor()
  await click('切换 3D')
  await page.locator('.scene-page.is-running').waitFor()
  await page.keyboard.press('Escape')
  const closeInspector = page.getByRole('button', { name: '关闭设备属性' })
  if (await closeInspector.count()) await closeInspector.click()
  await page.getByLabel('画面主题').selectOption('dark')
  await page.waitForTimeout(500)
  await page.screenshot({ path: '.qa/results/3d-editor-dark.png' })
  await click('保存')
  await page.reload()
  await click('3D')
  await page.locator('.tree-row').first().waitFor()
  assert.equal(await page.locator('.tree-row').count(), 10)
  assert.equal(await page.getByLabel('画面主题').inputValue(), 'dark')
  assert.equal(await page.getByLabel('设备名称统一字号（px）', { exact: true }).inputValue(), '18')
  assert.equal(await page.locator('.industrial-device-label', { hasText: '输送泵 P-101' }).locator('strong').evaluate(node => getComputedStyle(node).fontSize), '26px')
  const restoredPanelSizes = await page.evaluate(() => ['.scene-library', '.scene-inspector', '.scene-data-dock'].map(selector => { const rect = document.querySelector(selector).getBoundingClientRect(); return [rect.width, rect.height] }))
  assert.equal(restoredPanelSizes[0][0], panelSizes[0][0])
  assert.equal(restoredPanelSizes[1][0], panelSizes[1][0])
  assert.equal(restoredPanelSizes[2][1], panelSizes[2][1])
  await page.locator('input[type="file"]').first().setInputFiles('.qa/results/scene-export.json')
  await waitText('.confirm-message', '0 处变量引用')
  await click('继续')
  await waitText('.scene-notice', '已导入 10 个')
  assert.equal(await page.getByLabel('设备名称统一字号（px）', { exact: true }).inputValue(), '18')
  assert.equal(await page.locator('.tree-row').count(), 10)
  await page.locator('a[href="/comm"]').click()
  assert.equal(await page.locator('.scene-page').count(), 0)
  assert.equal(await page.locator('.view-switch').count(), 0)
  await page.locator('a[href="/canvas"]').click()
  await page.locator('.industrial-webgl').waitFor()
  assert.equal(socketCount, 2, 'only one realtime socket per page load; switching does not reconnect')
  assert.deepEqual(writes, [], 'UI verification must not send any controller commands')
  assert.deepEqual(errors, [], 'no browser or Three.js runtime errors')
  console.log(JSON.stringify({ passed: true, checks: 'stable 3D panel resizing, no product demo scene, canvas device double-click focus, Ctrl+C/V/Z editing, responsive vertical device-status grid, shared 2D/3D toolbar, universal component naming, animated camera views, collapsible library/tree, real 3D hover preview, enlarged viewport/dock text, four panel resize handles, size persistence, canvas-only application mode, actual Chinese/Latin fonts, shared data, project/JSON roundtrip, route scope, WebSocket reuse', socketCount, writes, errors }))
} catch (error) {
  await page.screenshot({ path: '.qa/results/failure.png' }).catch(() => {})
  console.error('Browser errors:', errors)
  throw error
} finally {
  await browser.close()
  await new Promise(done => server.close(done))
}
