param(
    [string]$DistDir = "",
    [string]$OutFile = ""
)

$ErrorActionPreference = "Stop"

$Root = Resolve-Path (Join-Path $PSScriptRoot "..")
if ([string]::IsNullOrWhiteSpace($DistDir)) {
    $DistDir = Join-Path $Root "frontend\dist"
}
if ([string]::IsNullOrWhiteSpace($OutFile)) {
    $OutFile = Join-Path $Root "backend\generated\frontend_assets.cpp"
}

$DistPath = Resolve-Path $DistDir
$DistFullPath = $DistPath.ProviderPath.TrimEnd("\", "/")
$OutDir = Split-Path -Parent $OutFile
New-Item -ItemType Directory -Force -Path $OutDir | Out-Null

function Get-ContentType([string]$Path) {
    switch ([System.IO.Path]::GetExtension($Path).ToLowerInvariant()) {
        ".html" { return "text/html; charset=utf-8" }
        ".js"   { return "application/javascript; charset=utf-8" }
        ".css"  { return "text/css; charset=utf-8" }
        ".json" { return "application/json; charset=utf-8" }
        ".svg"  { return "image/svg+xml" }
        ".png"  { return "image/png" }
        ".jpg"  { return "image/jpeg" }
        ".jpeg" { return "image/jpeg" }
        ".ico"  { return "image/x-icon" }
        ".woff2"{ return "font/woff2" }
        default { return "application/octet-stream" }
    }
}

function Escape-CppString([string]$Value) {
    return $Value.Replace("\", "\\").Replace('"', '\"')
}

$Files = Get-ChildItem -Path $DistPath -File -Recurse |
    Where-Object { $_.Extension -ne ".map" } |
    Sort-Object FullName

if (-not ($Files | Where-Object { $_.Name -eq "index.html" })) {
    throw "index.html not found in $DistPath. Run npm.cmd run build in frontend first."
}

$Builder = [System.Text.StringBuilder]::new()
[void]$Builder.AppendLine("// Generated by tools/embed_frontend.ps1. Do not edit manually.")
[void]$Builder.AppendLine("#include ""frontend_assets.h""")
[void]$Builder.AppendLine()
[void]$Builder.AppendLine("namespace {")

$Entries = @()
for ($i = 0; $i -lt $Files.Count; $i++) {
    $File = $Files[$i]
    $RelPath = $File.FullName.Substring($DistFullPath.Length).TrimStart("\", "/").Replace("\", "/")
    $Bytes = [System.IO.File]::ReadAllBytes($File.FullName)
    $ArrayName = "asset_$i"

    [void]$Builder.AppendLine("alignas(16) const unsigned char $ArrayName[] = {")
    for ($offset = 0; $offset -lt $Bytes.Length; $offset += 24) {
        $End = [Math]::Min($offset + 23, $Bytes.Length - 1)
        $Hex = for ($j = $offset; $j -le $End; $j++) {
            "0x" + $Bytes[$j].ToString("X2")
        }
        [void]$Builder.AppendLine("    " + ($Hex -join ", ") + ",")
    }
    [void]$Builder.AppendLine("};")
    [void]$Builder.AppendLine()

    $Entries += [pscustomobject]@{
        Path = Escape-CppString $RelPath
        ContentType = Escape-CppString (Get-ContentType $RelPath)
        ArrayName = $ArrayName
        Size = $Bytes.Length
    }
}

[void]$Builder.AppendLine("const EmbeddedFrontendAsset kEmbeddedAssets[] = {")
foreach ($Entry in $Entries) {
    [void]$Builder.AppendLine("    { ""$($Entry.Path)"", ""$($Entry.ContentType)"", $($Entry.ArrayName), $($Entry.Size) },")
}
[void]$Builder.AppendLine("};")
[void]$Builder.AppendLine()
[void]$Builder.AppendLine("} // namespace")
[void]$Builder.AppendLine()
[void]$Builder.AppendLine("bool embeddedFrontendAvailable() {")
[void]$Builder.AppendLine("    return true;")
[void]$Builder.AppendLine("}")
[void]$Builder.AppendLine()
[void]$Builder.AppendLine("const EmbeddedFrontendAsset* findEmbeddedFrontendAsset(const std::string& path) {")
[void]$Builder.AppendLine("    std::string clean = path;")
[void]$Builder.AppendLine("    while (!clean.empty() && clean.front() == '/') clean.erase(clean.begin());")
[void]$Builder.AppendLine("    if (clean.empty()) clean = ""index.html"";")
[void]$Builder.AppendLine("    for (const auto& asset : kEmbeddedAssets) {")
[void]$Builder.AppendLine("        if (clean == asset.path) return &asset;")
[void]$Builder.AppendLine("    }")
[void]$Builder.AppendLine("    return nullptr;")
[void]$Builder.AppendLine("}")

[System.IO.File]::WriteAllText($OutFile, $Builder.ToString(), [System.Text.UTF8Encoding]::new($false))
Write-Host "Embedded $($Entries.Count) frontend files into $OutFile"
